name: "📚 Documentation"
description: "Report an issue related to documentation"
title: "📚 Documentation: "
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our bug report form 🙏

        Use this template to notfy us if you found a bug.

        To make it easier for us to help you please enter detailed information below.

  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: "💭 Description"
      description: "Give us a clear and concise description of what the issue is."
      placeholder: "Documentation should not ..."

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you checked if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar bug?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      description: "This is our [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)."
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - label: "I've read the Code of Conduct"
          required: true
